### ISSUE TITLE
To-Do List (Sept. 24th)

### ISSUE THREAD

**Issue by Linda0501** [clrkwng/kickstarter-success#2]
- [ ] Research more data to determine what the focus question should be 

- [ ] Suggestions and ideas for the focus question 

- [ ] Learn how to use GitHub (if needed)

- [ ] Email Alex

**Comment by Dominicliu129** [comment]
Here are some datasets that might be useful:
1. [Top 4000 most backed projects ever on Kickstarter](https://www.kaggle.com/socathie/kickstarter-project-statistics#most_backed.csv)(slightly more categories than the 300,000-project one)
2. [Kickstarter Campaign Success](https://data.world/rdowns26/kickstarter-campaigns)  ("What insights around Kickstarter campaign success can we discover, and how can we proactively predict campaign outcome?" -- A project basically addressing the same issue)
3. [Funding Successful Projects on Kickstarter](https://www.kaggle.com/codename007/funding-successful-projects/insights) ("Predict  if a project will get successfully funded or not using labeled data"-- donno how the model works but the data inside might be useful)

**Comment by cahom** [comment]
[Kickstarter projects in CSV/JSON](https://webrobots.io/kickstarter-datasets/rl)
Recent Datasets of 2018, and consist of 35 features within a single kickstarter.

One approach is to compare the top 4000 data set with another data set, such as 
[Kickstarter Project Statistics 4000 live projects plus 4000 most backed projects](https://www.kaggle.com/socathie/kickstarter-project-statistics)

Facotors suggested toward the focus questions:
- Number of campaigns the project owner had previously backed
- Number of images on the campaign profile 
- Funding goal 
- Category
- Campaign duration 
- Number of campaigns the project owner had previously created 
- Number of project collaborators or supporters
- Length of the campaign title 
- Number of words in the title that matched the 4000 most backed campaigns

**Comment by Linda0501** [comment]
1. https://towardsdatascience.com/predicting-the-success-of-kickstarter-campaigns-3f4a976419b9 (a pretty good article about the overall process of the project we are doing)

2. https://webrobots.io/kickstarter-datasets/ (This website contains a massive amount of data on Kickstarter projects from 2014 to 2018, which I think can be the time span that we work on. The data sets include a variety of categories.)

**Comment by Linda0501** [comment]
1. https://www.kickstarter.com/help/stats (This website has the number of cases that are successful.)
