### ISSUE TITLE
To-Do List (Oct. 1st)

### ISSUE THREAD

**Issue by Linda0501** [clrkwng/kickstarter-success#3]
- [ ] Finish Intermediate Python Programming (DataCamp)

- [ ] Python Data Science Toolbox Part 1 (DataCamp)

- [ ] Python Data Science Toolbox Part 2 (DataCamp)

- [ ] Comes up with suggestions for focus question for our project
