### ISSUE TITLE
To-Do (Nov. 19th)

### ISSUE THREAD

**Issue by clrkwng** [clrkwng/kickstarter-success#9]
- [ ] Description for your aspects done by next Monday's meeting (Nov. 26th)

- [ ] PowerPoint done for next Monday's meeting (Nov. 26th)

- [ ] Jupyter Notebook Report done next Monday's meeting (Nov. 26th)
